<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config['RENTAL_DELIVERY_ITEMS']['columns_list']	= array(
	array(
		'display_name'		=> 'Id',
		'tbl_field_name' 	=> 'id',
		'field_key' 		=> 'id',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0, 
		'create_flag'		=> 0,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Copy From Type',
		'tbl_field_name' 	=> 'copy_from_type',
		'field_key' 		=> 'copyFromType',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Copy From Id',
		'tbl_field_name' 	=> 'copy_from_id',
		'field_key' 		=> 'copyFromId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Rental delivery Id',
		'tbl_field_name' 	=> 'rental_delivery_id',
		'field_key' 		=> 'rentalDeliveryId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Rental Item Id',
		'tbl_field_name' 	=> 'rental_item_id',
		'field_key' 		=> 'rentalItemId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Quantity',
		'tbl_field_name' 	=> 'quantity',
		'field_key' 		=> 'quantity',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Duration',
		'tbl_field_name' 	=> 'duration',
		'field_key' 		=> 'duration',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Start Date',
		'tbl_field_name' 	=> 'start_date',
		'field_key' 		=> 'startDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'End Date',
		'tbl_field_name' 	=> 'end_date',
		'field_key' 		=> 'endDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Ship Date',
		'tbl_field_name' 	=> 'ship_date',
		'field_key' 		=> 'shipDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Return Date',
		'tbl_field_name' 	=> 'return_date',
		'field_key' 		=> 'returnDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Po Expiry Date',
		'tbl_field_name' 	=> 'po_expiry_date',
		'field_key' 		=> 'poExpiryDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Equipment Card',
		'tbl_field_name' 	=> 'rental_equipment_id',
		'field_key' 		=> 'rentalEquipmentId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Uom Id',
		'tbl_field_name' 	=> 'uom_id',
		'field_key' 		=> 'uomId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Unit Price',
		'tbl_field_name' 	=> 'unit_price',
		'field_key' 		=> 'unitPrice',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Hsn Id',
		'tbl_field_name' 	=> 'hsn_id',
		'field_key' 		=> 'hsnId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Discount Percentage',
		'tbl_field_name' 	=> 'discount_percentage',
		'field_key' 		=> 'discountPercentage',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Tax Id',
		'tbl_field_name' 	=> 'tax_id',
		'field_key' 		=> 'taxId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	
	array(
		'display_name'		=> 'Item Tax Percentage',
		'tbl_field_name' 	=> 'item_tax_percentage',
		'field_key' 		=> 'itemTaxPercentage',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Item Tax Value',
		'tbl_field_name' 	=> 'item_tax_value',
		'field_key' 		=> 'itemTaxValue',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Total Item Amount',
		'tbl_field_name' 	=> 'total_item_amount',
		'field_key' 		=> 'totalItemAmount',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Distribution Rules Id',
		'tbl_field_name' 	=> 'distribution_rules_id',
		'field_key' 		=> 'distributionRulesId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Is Utilized',
		'tbl_field_name' 	=> 'is_utilized',
		'field_key' 		=> 'isUtilized',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Sap Id',
		'tbl_field_name' 	=> 'sap_id',
		'field_key' 		=> 'sapId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Posting Status',
		'tbl_field_name' 	=> 'posting_status',
		'field_key' 		=> 'postingStatus',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Sap Error',
		'tbl_field_name' 	=> 'sap_error',
		'field_key' 		=> 'sapError',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Created On',
		'tbl_field_name' 	=> 'created_on',
		'field_key' 		=> 'createdOn',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Created By',
		'tbl_field_name' 	=> 'created_by',
		'field_key' 		=> 'createdBy',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Updated On',
		'tbl_field_name' 	=> 'updated_on',
		'field_key' 		=> 'UpdatedOn',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Updated By',
		'tbl_field_name' 	=> 'updated_by',
		'field_key' 		=> 'UpdatedBy',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	)
);
/*////////////////////////////// END OF FILE //////////////////////////////*/