<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config['SALES_AR_CREDIT_MEMO']['excel_file_name']	= time() . '_SALES_AR_CREDIT_MEMO.xlsx';
$config['SALES_AR_CREDIT_MEMO']['columns_list']		= array(
	array(
		'display_name'		=> 'Id',
		'tbl_field_name' 	=> 'id',
		'field_key' 		=> 'id',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'		    => 1,
		'update_flag'		=> 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Document Number',
		'tbl_field_name' 	=> 'document_number',
		'field_key' 		=> 'documentNumber',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Document Numbering Id',
		'tbl_field_name' 	=> 'document_numbering_id',
		'field_key' 		=> 'documentNumberingId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Document Numbering Type',
		'tbl_field_name' 	=> 'document_numbering_type',
		'field_key' 		=> 'documentNumberingType',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 0,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'OverDue Value',
		'tbl_field_name' 	=> 'over_due_value',
		'field_key' 		=> 'overDueValue',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer BP Id',
		'tbl_field_name' 	=> 'customer_bp_id',
		'field_key' 		=> 'customerBpId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer Name',
		'tbl_field_name' 	=> 'customer_bp_name',
		'field_key' 		=> 'customerName',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer BP Contacts Id',
		'tbl_field_name' 	=> 'customer_bp_contacts_id',
		'field_key' 		=> 'customerBpContactsId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer Ship to BP Address Id',
		'tbl_field_name' 	=> 'customer_ship_to_bp_address_id',
		'field_key' 		=> 'customerShipToBpAddressId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer Ship to Address',
		'tbl_field_name' 	=> 'customer_ship_to_address',
		'field_key' 		=> 'customerShipToAddress',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer Bill to Id',
		'tbl_field_name' 	=> 'customer_bill_to_bp_address_id',
		'field_key' 		=> 'customerBillToBpAddressId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Customer Bill to Address',
		'tbl_field_name' 	=> 'customer_bill_to_address',
		'field_key' 		=> 'customerBillToAddress',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Currency Id',
		'tbl_field_name' 	=> 'currency_id',
		'field_key' 		=> 'currencyId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Currency Name',
		'tbl_field_name' 	=> 'currency_name',
		'field_key' 		=> 'currencyName',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Reference Number',
		'tbl_field_name' 	=> 'reference_number',
		'field_key' 		=> 'referenceNumber',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Posting Date',
		'tbl_field_name' 	=> 'posting_date',
		'field_key' 		=> 'postingDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Due Date',
		'tbl_field_name' 	=> 'due_date',
		'field_key' 		=> 'dueDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Document Date',
		'tbl_field_name' 	=> 'document_date',
		'field_key' 		=> 'documentDate',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'status',
		'tbl_field_name' 	=> 'status',
		'field_key' 		=> 'status',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 1,
			   'is_numeric' 	=> 1,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'status Name',
		'tbl_field_name' 	=> 'status_name',
		'field_key' 		=> 'statusName',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Remarks',
		'tbl_field_name' 	=> 'remarks',
		'field_key' 		=> 'remarks',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Udf Fields',
		'tbl_field_name' 	=> 'udf_fields',
		'field_key' 		=> 'udfFields',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Discount Percentage',
		'tbl_field_name' 	=> 'discount_percentage',
		'field_key' 		=> 'discountPercentage',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Discount Value',
		'tbl_field_name' 	=> 'discount_value',
		'field_key' 		=> 'discountValue',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),

	array(
		'display_name'		=> 'Tax Percentage',
		'tbl_field_name' 	=> 'tax_percentage',
		'field_key' 		=> 'taxPercentage',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Total Amount',
		'tbl_field_name' 	=> 'total_amount',
		'field_key' 		=> 'totalAmount',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Total Before Discount',
		'tbl_field_name' 	=> 'total_before_discount',
		'field_key' 		=> 'totalBeforeDiscount',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'is Draft',
		'tbl_field_name' 	=> 'is_draft',
		'field_key' 		=> 'isDraft',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			   'is_mandatory'   => 1,
			   'is_numeric' 	=> 0,
			   'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Branch Id',
		'tbl_field_name' 	=> 'branch_id',
		'field_key' 		=> 'branchId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Sales Emp Id',
		'tbl_field_name' 	=> 'sales_emp_id',
		'field_key' 		=> 'salesEmpId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),	
	array(
		'display_name'		=> 'distribution_rules_id',
		'tbl_field_name' 	=> 'distribution_rules_id',
		'field_key' 		=> 'distributionRulesId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Payment Terms Id',
		'tbl_field_name' 	=> 'payment_terms_id',
		'field_key' 		=> 'paymentTermsId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Payment Method Id',
		'tbl_field_name' 	=> 'payment_method_id',
		'field_key' 		=> 'paymentMethodId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Tax Code',
		'tbl_field_name' 	=> 'tax_code',
		'field_key' 		=> 'taxCode',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Original Reference Number',
		'tbl_field_name' 	=> 'original_ref_number',
		'field_key' 		=> 'originalRefNumber',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Original Reference Date',
		'tbl_field_name' 	=> 'original_ref_date',
		'field_key' 		=> 'originalRefDate',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Issuing Note Id',
		'tbl_field_name' 	=> 'issuing_note_id',
		'field_key' 		=> 'issuingNoteId',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Rounding',
		'tbl_field_name' 	=> 'rounding',
		'field_key' 		=> 'rounding',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Rounding Flag',
		'tbl_field_name' 	=> 'rounding_flag',
		'field_key' 		=> 'roundingFlag',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Sap Id',
		'tbl_field_name' 	=> 'sap_id',
		'field_key' 		=> 'sapId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Approval Status',
		'tbl_field_name' 	=> 'approval_status',
		'field_key' 		=> 'approvalStatus',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'		    => 1,
		'update_flag'		=> 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Posting Status',
		'tbl_field_name' 	=> 'posting_status',
		'field_key' 		=> 'postingStatus',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Sap Error',
		'tbl_field_name' 	=> 'sap_error',
		'field_key' 		=> 'sapError',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Sales AR DP Invoice id',
		'tbl_field_name' 	=> 'sales_ar_dp_invoice_id',
		'field_key' 		=> 'salesArDpInvoiceId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),	
	array(
		'display_name'		=> 'Sales AR DP Invoice Used Amount',
		'tbl_field_name' 	=> 'sales_ar_dp_invoice_used_amount',
		'field_key' 		=> 'salesArDpInvoiceUsedAmount',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Sales Ar Dp Invoice Used Tax Amount',
		'tbl_field_name' 	=> 'sales_ar_dp_invoice_used_tax_amount',
		'field_key' 		=> 'salesArDpInvoiceUsedTaxAmount',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Created On',
		'tbl_field_name' 	=> 'created_on',
		'field_key' 		=> 'createdOn',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Created By',
		'tbl_field_name' 	=> 'created_by',
		'field_key' 		=> 'createdBy',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Updated On',
		'tbl_field_name' 	=> 'updated_on',
		'field_key' 		=> 'UpdatedOn',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Updated By',
		'tbl_field_name' 	=> 'updated_by',
		'field_key' 		=> 'UpdatedBy',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	)
);

/*////////////////////////////// END OF FILE //////////////////////////////*/