<?php
// EMPLOYEE LIST 
$config['EMPLOYEE_PROFILE']['excel_file_name']	= time() . '_employee_list.xlsx';
$config['EMPLOYEE_PROFILE']['columns_list']	= array(
	array(
		'display_name'		=> 'Employee Code',
		'tbl_field_name' 	=> 'emp_code',
		'field_key' 		=> 'empCode',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'First Name',
		'tbl_field_name' 	=> 'first_name',
		'field_key' 		=> 'firstName',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Last Name',
		'tbl_field_name' 	=> 'last_name',
		'field_key' 		=> 'lastName',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Email Id',
		'tbl_field_name' 	=> 'email_id',
		'field_key' 		=> 'emailId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Country Code',
		'tbl_field_name' 	=> 'primary_country_code',
		'field_key' 		=> 'primaryCountryCode',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Contact Number',
		'tbl_field_name' 	=> 'primary_contact_no',
		'field_key' 		=> 'primaryContactNo',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'status',
		'tbl_field_name' 	=> 'status',
		'field_key' 		=> 'status',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'User Image',
		'tbl_field_name' 	=> 'profile_img',
		'field_key' 		=> 'userImage',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Reporting Manager Id',
		'tbl_field_name' 	=> 'reporting_manager_id',
		'field_key' 		=> 'reportingManagerId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Branch Id',
		'tbl_field_name' 	=> 'branch_id',
		'field_key' 		=> 'branchId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Is User',
		'tbl_field_name' 	=> 'is_user',
		'field_key' 		=> 'isUser',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Designation Id',
		'tbl_field_name' 	=> 'designation_id',
		'field_key' 		=> 'designationId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Access Control Name',
		'tbl_field_name' 	=> 'access_control_id',
		'field_key' 		=> 'accessControlId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'System User',
		'tbl_field_name' 	=> 'system_user',
		'field_key' 		=> 'systemUser',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Employee Type Id',
		'tbl_field_name' 	=> 'employee_type_id',
		'field_key' 		=> 'employeeTypeId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Business Partner Id',
		'tbl_field_name' 	=> 'business_partner_id',
		'field_key' 		=> 'businessPartnerId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Distrubution Rules Id',
		'tbl_field_name' 	=> 'distribution_rules_id',
		'field_key' 		=> 'distributionRulesId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Employee Name',
		'tbl_field_name' 	=> 'emp_name',
		'field_key' 		=> 'empName',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Status Name',
		'tbl_field_name' 	=> 'status_name',
		'field_key' 		=> 'statusName',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Branch Name',
		'tbl_field_name' 	=> 'branch_info_values',
		'field_key' 		=> 'branchInfoValues',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Distribution Info',
		'tbl_field_name' 	=> 'distribution_rules_values',
		'field_key' 		=> 'distributionRulesValues',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Employee Type Name',
		'tbl_field_name' 	=> 'employee_type_name',
		'field_key' 		=> 'employeeTypeName',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Reporting Manager Name',
		'tbl_field_name' 	=> 'reporting_manager_name',
		'field_key' 		=> 'reportingManagerName',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'IS Application User',
		'tbl_field_name' 	=> 'is_user_value',
		'field_key' 		=> 'isUserValue',
		'field_type' 	 	=> '',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
		)
	),	
	array(
		'display_name'		=> 'Sap Id',
		'tbl_field_name' 	=> 'sap_id',
		'field_key' 		=> 'sapId',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Posting Status',
		'tbl_field_name' 	=> 'posting_status',
		'field_key' 		=> 'postingStatus',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Sap Error',
		'tbl_field_name' 	=> 'sap_error',
		'field_key' 		=> 'sapError',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			'is_mandatory'   => 0,
			'is_numeric' 	 => 0,
			'is_date'        => 0,
	 )
	),
	array(
		'display_name'		=> 'Created On',
		'tbl_field_name' 	=> 'created_on',
		'field_key' 		=> 'createdOn',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			   'is_mandatory'   => 0,
			   'is_numeric' 	=> 0,
			   'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Created By',
		'tbl_field_name' 	=> 'created_by',
		'field_key' 		=> 'createdBy',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 1,
		'update_flag'       => 0,
		'field_validation'	=> array(
			   'is_mandatory'   => 0,
			   'is_numeric' 	=> 0,
			   'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Updated On',
		'tbl_field_name' 	=> 'updated_on',
		'field_key' 		=> 'UpdatedOn',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			   'is_mandatory'   => 0,
			   'is_numeric' 	=> 0,
			   'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Territory Name',
		'tbl_field_name' 	=> 'territory_id',
		'field_key' 		=> 'territoryId',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'			=> 1,
		'update_flag'       => 1,
		'field_validation'	=> array(
			   'is_mandatory'   => 0,
			   'is_numeric' 	=> 1,
			   'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Updated By',
		'tbl_field_name' 	=> 'updated_by',
		'field_key' 		=> 'UpdatedBy',
		'field_type' 	 	=> 'number',
		'search_flag'		=> 1,
		'sort_flag'			=> 1,
		'excel_flag'		=> 0,
		'create_flag'		=> 0,
		'edit_flag'			=> 0,
		'update_flag'       => 0,
		'field_validation'	=> array(
			   'is_mandatory'   => 0,
			   'is_numeric' 	=> 0,
			   'is_date'        => 0,
		)
	),
	array(
		'display_name'		=> 'Remarks',
		'tbl_field_name' 	=> 'remarks',
		'field_key' 		=> 'remarks',
		'field_type' 	 	=> 'alpha',
		'search_flag'		=> 0,
		'sort_flag'			=> 0,
		'excel_flag'		=> 1,
		'create_flag'		=> 1,
		'edit_flag'		    => 1,
		'update_flag'		=> 1,
		'field_validation'	=> array(
			   'is_mandatory'   => 0,
			   'is_numeric' 	=> 0,
			   'is_date'        => 0,
		)
	)
);
?>